name: Generate Datas

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite (UTC)
  workflow_dispatch: # Permite executar manualmente pelo GitHub

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Gabriel-br2
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
